language: rust
cache: cargo

jobs:
  include:
    - stage: build
      before_install: rustup component add rustfmt clippy
      script:
        - cargo fmt --all --verbose -- --check
        - cargo build --all --all-targets --verbose
        - cargo clippy --all --all-targets -- -D warnings
        - cargo test --all --all-targets --verbose
