language: rust
cache: cargo

jobs:
  include:
    - stage: format
      before_install: rustup component add rustfmt
      script: cargo fmt --verbose -- --check --verbose

    - stage: lint
      before_install: rustup component add clippy
      script: cargo clippy --all-targets -- -D warnings

    - stage: test
      script: cargo test --all --verbose
