language: rust
cache: cargo

jobs:
  include:
    - stage: build
      name: format
      before_install: rustup component add rustfmt
      script: cargo fmt --verbose -- --check
    - name: lint
      before_install: rustup component add clippy
      script: cargo clippy --all-targets -- -D warnings
    - name: test
      script: cargo test --all --verbose
