merge_derives = true

# Unstable options — uncomment when these become stable.
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_strings = true
# merge_imports = true
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true
# unstable_features = true
# use_field_init_shorthand = true
# use_try_shorthand = true
# wrap_comments = true
